[package]
name = "size-display"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"
description = "Display file sizes in human-readable form"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
